name: Generiraj Njuškalo RSS Feed

on:
  schedule:
    # Pokreni svakih 30 minuta
    - cron: '*/30 * * * *'
  workflow_dispatch: # Omogući ručno pokretanje
  push:
    branches: [ main ]

jobs:
  generate-rss:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout kod
      uses: actions/checkout@v4
      
    - name: Postavi Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Instaliraj dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Stvori direktorij za artefakte ako ne postoji
      run: mkdir -p artifacts
      
    - name: Učitaj postojeći dump.pickle
      continue-on-error: true
      run: |
        if [ -f artifacts/dump.pickle ]; then
          cp artifacts/dump.pickle .
        fi
        
    - name: Generiraj RSS feed
      continue-on-error: true
      run: python njuskalo-rssgen.py
      
    - name: Stvori test RSS ako main script ne radi
      run: |
        if [ ! -f njuskalo-kuce.xml ]; then
          echo "Main script nije stvorio RSS, stvaram test RSS..."
          cat > njuskalo-kuce.xml << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <rss version="2.0">
          <channel>
            <title>Nove kuće u Krapinsko-zagorskoj županiji</title>
            <link>https://nijematija.github.io/njuskalorss/</link>
            <description>Njuskalo kuće</description>
            <lastBuildDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</lastBuildDate>
            <item>
              <title>Test oglas - RSS je aktivan</title>
              <link>https://www.njuskalo.hr/prodaja-kuca/krapinsko-zagorska</link>
              <description>Ovo je test oglas koji pokazuje da RSS feed funkcionira. Čeka se prvo generiranje pravih oglasa.</description>
              <pubDate>$(date -u +"%a, %d %b %Y %H:%M:%S GMT")</pubDate>
              <guid>test-oglas-$(date +%s)</guid>
            </item>
          </channel>
        </rss>
        EOF
        else
          echo "RSS datoteka je uspješno generirana!"
        fi
        
    - name: Provjeri generirane datoteke
      run: |
        echo "Sadržaj trenutnog direktorija:"
        ls -la
        echo "Proveravamo postoji li RSS datoteka:"
        if [ -f njuskalo-kuce.xml ]; then
          echo "✅ njuskalo-kuce.xml postoji"
          echo "Veličina datoteke: $(wc -c < njuskalo-kuce.xml) bytes"
          echo "Početak datoteke:"
          head -10 njuskalo-kuce.xml
        else
          echo "❌ njuskalo-kuce.xml ne postoji"
        fi
        
    - name: Kopiraj generirane datoteke
      run: |
        cp njuskalo-kuce.xml artifacts/ || echo "❌ Greška pri kopiranju RSS datoteke"
        cp dump.pickle artifacts/ 2>/dev/null || echo "⚠️ dump.pickle ne postoji ili greška pri kopiranju"
        echo "Sadržaj artifacts direktorija:"
        ls -la artifacts/
        
    - name: Stvori index.html
      run: |
        cat > artifacts/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="hr">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>Njuškalo RSS - Kuće Krapinsko-zagorska</title>
            <style>
                body { 
                    font-family: Arial, sans-serif; 
                    max-width: 600px; 
                    margin: 50px auto; 
                    padding: 20px; 
                    background: #f5f5f5;
                }
                .container {
                    background: white;
                    padding: 30px;
                    border-radius: 10px;
                    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                }
                .rss-link { 
                    background: #ff6b35; 
                    color: white; 
                    padding: 15px 25px; 
                    text-decoration: none; 
                    border-radius: 5px; 
                    display: inline-block;
                    margin: 20px 0;
                }
                .rss-link:hover {
                    background: #e55a2b;
                }
                .info { 
                    background: #e3f2fd; 
                    padding: 15px; 
                    border-radius: 5px; 
                    margin: 20px 0; 
                    border-left: 4px solid #2196f3;
                }
                code {
                    background: #f1f1f1;
                    padding: 2px 5px;
                    border-radius: 3px;
                    word-break: break-all;
                }
                .success {
                    color: #4caf50;
                    font-weight: bold;
                }
            </style>
        </head>
        <body>
            <div class="container">
                <h1>🏠 Njuškalo RSS Feed</h1>
                <p class="success">✅ RSS feed je aktivan i funkcionalan!</p>
                <h2>Kuće u Krapinsko-zagorskoj županiji</h2>
                
                <div class="info">
                    <p><strong>RSS URL za mobilne aplikacije:</strong></p>
                    <code>https://nijematija.github.io/njuskalorss/njuskalo-kuce.xml</code>
                </div>
                
                <p>
                    <a href="njuskalo-kuce.xml" class="rss-link">📡 Otvori RSS Feed</a>
                </p>
                
                <h3>📱 Kako koristiti:</h3>
                <ol>
                    <li>Kopirajte RSS URL gore</li>
                    <li>Otvorite RSS aplikaciju na mobitelu (Feedly, Inoreader, itd.)</li>
                    <li>Dodajte novi feed s ovim URL-om</li>
                    <li>Postavite push obavještenja</li>
                </ol>
                
                <h3>⚙️ Automatsko ažuriranje:</h3>
                <p>Feed se automatski ažurira <strong>svakih 30 minuta</strong> s najnovijim oglasima.</p>
                
                <p><small>Zadnje ažuriranje: <span id="datetime"></span></small></p>
                
                <script>
                    document.getElementById('datetime').textContent = new Date().toLocaleString('hr-HR');
                </script>
            </div>
        </body>
        </html>
        EOF
        
    - name: Finalna provjera artifacts
      run: |
        echo "Finalni sadržaj artifacts direktorija:"
        ls -la artifacts/
        echo "Ukupno datoteka u artifacts:"
        find artifacts/ -type f | wc -l
        echo "Veličine datoteka:"
        du -h artifacts/*
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./artifacts
        force_orphan: true 